image: openjdk:12
stages:
  - test
  - build

variables:
  GRADLE_USER_HOME: "${CI_PROJECT_DIR}/.gradle_home"

cache:
  paths:
    - ".gradle_home"
    - ".gradle"

test:
  stage: test
  script:
    - "./gradlew test"

build_snapshot:
  stage: build
  only:
    - master
  except:
    - tags
  variables:
    SNAPSHOT_VERSION: "SNAPSHOT_${CI_PIPELINE_ID}+${CI_COMMIT_SHORT_SHA}"
  script:
    - "./gradlew :buildPlugin"
  artifacts:
    name: "phabricator-pluigin-${SNAPSHOT_VERSION}"
    paths:
      - "build/distributions/*.zip"
    expire_in: 3 months

build_tag:
  stage: build
  only:
    - tags
  script:
    - "./gradlew :buildPlugin"
  artifacts:
    name: "phabricator-plugin-${CI_COMMIT_TAG}"
    expire_in: 1 year
    paths:
      - "build/distributions/*.zip"
