version: '3.1'
services:
  phabricator:
    image: hachque/phabricator
    ports:
      - 80:80
      - 443:443
    volumes:
      - phabricator:/repos
    environment:
      - PHABRICATOR_HOST=phabricator.local
      - PHABRICATOR_REPOSITORY_PATH=/repos
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASS=root
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    image: mysql:5.7.14
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
volumes:
  phabricator:
  db:
